// Copy for the architecture page and the ADR pages. The build fills every
// empty data-i18n element and SVG label from COPY.en, so the page reads without
// JS; architecture.js switches to COPY.et. ADR bodies stay English.
export const COPY = {
  en: {
    title: 'Estate architecture | KHE',
    description: 'How the KHE estate is built: context, building blocks, key flows, quality goals, the architecture decisions and the known limits.',
    siteNavAria: 'Site navigation',
    homeLabel: 'KHE home',
    languageLabel: 'Language',
    siteKicker: 'KHE',
    siteTitle: 'Architecture',
    decisionSiteTitle: 'Decision',
    kicker: 'Estate architecture',
    headline: 'How the KHE estate is built',
    lead: 'The KHE estate is a small software portfolio and the home infrastructure that runs it: the products, a public website and the platform beneath them, built and run by one person. Everything public runs on one host at home, reachable only through an outbound tunnel, and every change reaches it from git. This page is the hand-over: what the estate is built from, why it is the way it is, how it stays up and where it is still weak.',
    tocLabel: 'On this page',
    factsLabel: 'The estate in numbers',
    factRepos: 'repositories',
    factProducts: 'products',
    factServices: 'services on the host',
    factDecisions: 'architecture decisions',
    factPorts: 'open inbound ports',
    factsNote: 'Counted at build time from khe-architecture and khe-homelab.',


    contextTitle: 'Context',
    contextBody: 'Three groups of people use the estate. The household uses the family services and the private apps, public visitors read the website and play the games, and invited guests open a trip that has been shared with them. The estate leans on a few external services: Cloudflare for DNS, the edge and sign-in, GitHub for code, CI and the container registry, Cloudflare R2 for offsite backups, Telegram for alerts, AI model APIs for the adventure game, and Elering for metered energy data.',
    viewContextTitle: 'Context diagram',
    viewContextDesc: 'The estate, the people who use it and the external services it depends on.',
    elHousehold: 'Household',
    elHouseholdSub: 'family services, private apps',
    elVisitors: 'Public visitors',
    elVisitorsSub: 'website and games',
    elGuests: 'Trip guests',
    elGuestsSub: 'a trip shared with them',
    groupPeople: 'People',
    groupExternal: 'External services',
    elEstate: 'KHE estate',
    elEstateSub: 'products and the platform at home',
    elCloudflare: 'Cloudflare',
    elCloudflareSub: 'DNS, edge, sign-in',
    elGithub: 'GitHub',
    elGithubSub: 'code, CI, images',
    elR2: 'Cloudflare R2',
    elR2Sub: 'offsite backups',
    elTelegram: 'Telegram',
    elTelegramSub: 'alerts',
    elAiApis: 'AI model APIs',
    elAiApisSub: 'game narration',
    elElering: 'Elering',
    elEleringSub: 'energy data',
    relHousehold: 'uses',
    relVisitors: 'read, play',
    relGuests: 'open a trip',

    blocksTitle: 'Building blocks',
    blocksBody: 'The estate has four parts. The products are what people use. The platform in khe-homelab runs them: one host, one Docker VM, every service a Compose stack. House automation runs on the same platform. The meta layer holds what spans the repositories: the agent workspace, this architecture and the private working notes.',
    viewBlocksTitle: 'Building blocks',
    viewBlocksDesc: 'Products, platform, house automation and the meta layer, and how they relate.',
    groupProducts: 'Products',
    groupPlatform: 'Platform (khe-homelab)',
    groupHouse: 'House automation',
    groupMeta: 'Meta layer',
    elStudySub: 'learning games',
    elAdventureSub: 'AI party game',
    elTripsSub: 'family trip atlas',
    elSitesSub: 'khe.ee and games hub',
    elEdge: 'Ingress',
    elEdgeSub: 'tunnel, reverse proxy, DNS',
    elRuntime: 'App runtime',
    elRuntimeSub: 'sites, games, trips',
    elFamily: 'Family services',
    elFamilySub: 'photo library',
    elObservability: 'Observability',
    elObservabilitySub: 'logs, alerts',
    elBackup: 'Backup and restore',
    elBackupSub: 'nightly, offsite',
    elHouse: 'Home automation hub',
    elHouseSub: 'local devices only',
    elWorkspaceSub: 'agent workspace',
    elArchitectureSub: 'decisions, index',
    elMetaSub: 'roadmap, plans',
    elProfileSub: 'GitHub profile',
    elEstfeedSub: 'energy data for HA',
    relRunOn: 'run on',
    stacksLabel: 'Stacks',
    privateLabel: 'private',
    purposeKheStudy: 'Small learning games for the Estonian curriculum, served as a static app.',
    purposeKheAiAdventure: 'An AI-narrated pass-the-phone party game: a static frontend and a guarded AI proxy, both shipped as images.',
    purposeKheTrips: 'The family trip atlas, private behind Cloudflare Access. Single trips can be shared by link.',
    purposeKheSites: 'This website and the games hub: plain HTML and CSS, built by Node scripts.',
    purposeEdge: 'Public traffic through the outbound tunnel, the reverse proxy and DNS on the home network, and the core services: uptime checks, self-healing and the password vault.',
    purposeRuntime: 'The containers behind the public sites, the games, the shared pages and the trip atlas.',
    purposeFamily: 'The family photo library, with its own login.',
    purposeObservability: 'Every container\'s logs in one place, and alerts to a phone.',
    purposeBackup: 'Nightly database dumps and file backups shipped offsite, and a test restore every week.',
    purposeHouse: 'Home Assistant and its local integrations. The details stay private.',
    purposeKheWorkspace: 'The root an AI coding agent works in: the agent rules, the commit hooks and the list of repositories.',
    purposeKheArchitecture: 'The estate\'s architecture decisions and the estate index this page is built from.',
    purposeKheMeta: 'The private working layer: the roadmap, the plans and the house documentation.',
    purposeKhelias: 'The GitHub profile page.',
    purposeHaEstfeed: 'A fork of the Elering meter-data integration for Home Assistant.',

    flowsTitle: 'Key flows',
    requestTitle: 'Request path',
    requestBody: 'A visitor\'s request reaches Cloudflare first. The server at home keeps an outbound tunnel open, and Cloudflare sends each hostname down it to its container, so the home router forwards nothing. On the home network, local DNS answers the same names with the reverse proxy instead, so household devices stay on the LAN. Apps behind Cloudflare Access have no such shortcut.',
    viewRequestTitle: 'Request path',
    viewRequestDesc: 'A public request through Cloudflare and the tunnel, and a household request on the home network.',
    groupInternet: 'From the internet',
    groupHomeNetwork: 'On the home network',
    elVisitor: 'Visitor',
    elVisitorSub: 'any browser',
    elCfEdge: 'Cloudflare edge',
    elCfEdgeSub: 'TLS, Access',
    elTunnel: 'Tunnel',
    elTunnelSub: 'outbound only',
    elApp: 'App container',
    elAppSub: 'on the Docker VM',
    elLanClient: 'Household device',
    elLanClientSub: 'on the home network',
    elDns: 'Local DNS',
    elDnsSub: 'split-horizon',
    elProxy: 'Reverse proxy',
    elProxySub: 'wildcard certificate',
    relHttps: 'HTTPS',
    relPerHostname: 'per hostname',
    relLookup: 'name lookup',
    relPointsTo: 'points to',
    deliveryTitle: 'Delivery path',
    deliveryBody: 'A change starts as a local commit and goes live once a person pushes it. Container images are built and scanned on GitHub-hosted runners, published to GHCR with an SBOM and provenance, and pinned by digest in khe-homelab through a pull request that merges itself once its guard and attestation checks pass. A runner on the VM then pulls the pinned image. Static sites skip the registry: the same runner builds and copies them.',
    viewDeliveryTitle: 'Delivery path',
    viewDeliveryDesc: 'From a commit to a running container.',
    elCommit: 'Commit',
    elCommitSub: 'agent prepares,',
    elCommitSub2: 'person pushes',
    elCi: 'CI',
    elCiSub: 'GitHub-hosted runner',
    elCiSub2: 'build, scan, attest',
    elGhcr: 'GHCR',
    elGhcrSub: 'public images,',
    elGhcrSub2: 'tagged by commit',
    elPinPr: 'Pin PR',
    elPinPrSub: 'in khe-homelab,',
    elPinPrSub2: 'merges after checks',
    elDeploy: 'Deploy',
    elDeploySub: 'runner on the VM',
    elDeploySub2: 'pulls by digest',

    qualityTitle: 'Quality goals',
    qualityIntro: 'Five goals shape most of the decisions. Each row names the mechanism and where to check it.',
    qGoal: 'Goal',
    qMechanism: 'How it is met',
    qEvidence: 'Evidence',
    qSecurity: 'Security',
    qSecurityGoal: 'Nothing at home is reachable except through the edge.',
    qSecurityHow: 'No inbound ports, an outbound tunnel, Cloudflare Access in front of the private apps. Images are scanned before they are published and checked against their attestations before they are pinned.',
    qResilience: 'Resilience',
    qResilienceGoal: 'A fault is caught by the cheapest layer that can catch it.',
    qResilienceHow: 'Layered, from the hardware watchdog to an outside monitor:',
    qResilienceRestore: 'Database dumps go offsite every night, and one is restored every week.',
    qDelivery: 'Delivery',
    qDeliveryGoal: 'What runs is named in git.',
    qDeliveryHow: 'A push to main deploys. Images are pinned by digest, so a rollback is a git change and a rebuilt VM knows what to pull.',
    qOperability: 'Operability',
    qOperabilityGoal: 'One person runs it in spare time.',
    qOperabilityHow: 'One host, one Docker VM, every service a Compose stack. Logs are in one place and alerts reach one phone.',
    qCost: 'Cost',
    qCostGoal: 'Small and predictable.',
    qCostHow: 'The hardware is already at home, and free tiers cover the edge and CI. Offsite storage and AI usage are paid per use, and the game\'s AI proxy has a daily spend cap.',
    readmeResilience: 'khe-homelab Resilience',
    restoreWorkflow: 'weekly restore check',

    decisionsTitle: 'Decisions',
    decisionsIntro: 'The estate\'s architecture decisions live in <a href="https://github.com/khelias/khe-architecture">khe-architecture</a> and are published here in full, one page each. Superseded decisions stay, with a link to the one that replaced them.',
    decisionsInEnglish: 'Decisions are kept in English.',
    regTitle: 'Decision',
    regStatus: 'Status',
    regDate: 'Date',
    statusAccepted: 'Accepted',
    statusProposed: 'Proposed',
    statusSuperseded: 'Superseded',
    statusDeprecated: 'Deprecated',
    productDecisions: 'The products keep their own decisions in their repositories:',

    operatingTitle: 'Operating model',
    operatingBody: 'An AI coding agent prepares the work and a person ships it. A non-trivial change starts as a written plan, which the person turns into a goal for the agent to carry out. Every code change is reviewed against its plan, and every commit passes a gate that runs the repository\'s own check and scans for personal data. Only a person pushes, and a push to main is a deploy.',
    viewOperatingTitle: 'Operating model',
    viewOperatingDesc: 'What the agent does and what the person does, from plan to deploy.',
    laneAgent: 'Agent',
    laneOperator: 'Person',
    elPlan: 'Plan',
    elPlanSub: 'written to a file',
    elApprove: 'Goal',
    elApproveSub: 'the plan, approved',
    elExecute: 'Execute',
    elExecuteSub: 'local changes',
    elReview: 'Review',
    elReviewSub: 'diff against the plan',
    elGate: 'Commit gate',
    elGateSub: 'check, personal-data scan',
    elPush: 'Push',
    elPushSub: 'only a person; it deploys',

    limitsTitle: 'Known limits and direction',
    limitsIntro: 'What is still weak:',
    limit1: 'One host is a single point of failure. If it or the home line is down, every public site is down with it.',
    limit2: 'A full rebuild on an empty VM has not been rehearsed. Restores are tested every week, one database at a time, but the rebuild as a whole is unproven.',
    limit3: 'One site and one edge vendor. DNS, certificates, the tunnel and sign-in all depend on Cloudflare.',
    directionIntro: 'What comes next:',
    next1: 'A second home for the static sites, so they stay up when the homelab does not.',
    next2: 'A rebuild rehearsal, and the runbook written from it, before any data that is not the family\'s enters an app.',
    next3: 'The first app backend, for khe-trips, on the pattern of <a href="/architecture/decisions/004/">ADR-004</a> and <a href="/architecture/decisions/009/">ADR-009</a>.',
    next4: 'Measured numbers on this page, such as uptime and the restore history, each with its method.',

    backToRegister: 'All decisions',
    decisionKicker: 'Architecture decision',
    metaStatus: 'Status',
    metaDate: 'Date',
    metaSupersedes: 'Supersedes',
    metaSupersededBy: 'Superseded by',
    metaRelated: 'Related',
    supersededNotice: 'This decision is superseded by',
    sourceOnGithub: 'Source on GitHub',
  },
  et: {
    title: 'Arhitektuur | KHE',
    description: 'Kuidas KHE süsteemid on üles ehitatud: kontekst, ehitusplokid, põhivood, kvaliteedieesmärgid, arhitektuuriotsused ja teadaolevad piirangud.',
    siteNavAria: 'Lehe navigeerimine',
    homeLabel: 'KHE avaleht',
    languageLabel: 'Keel',
    siteKicker: 'KHE',
    siteTitle: 'Arhitektuur',
    decisionSiteTitle: 'Otsus',
    kicker: 'Süsteemide arhitektuur',
    headline: 'Kuidas KHE süsteemid on üles ehitatud',
    lead: 'KHE süsteemid on väike tarkvaraportfell koos seda käitava koduse taristuga: tooted, avalik veebileht ja nende all olev platvorm, mida ehitab ja haldab üks inimene. Kõik avalik töötab ühes kodus asuvas serveris, kuhu pääseb ainult väljuva tunneli kaudu, ja iga muudatus jõuab sinna gitist. See leht on üleandmisdokument: millest süsteemid koosnevad, miks need on just sellised, kuidas need töös püsivad ja kus on veel nõrkusi.',
    tocLabel: 'Sellel lehel',
    factsLabel: 'Süsteemid arvudes',
    factRepos: 'koodivaramut',
    factProducts: 'toodet',
    factServices: 'teenust serveris',
    factDecisions: 'arhitektuuriotsust',
    factPorts: 'avatud sissetulevat porti',
    factsNote: 'Loendatud ehitamise ajal khe-architecture\'i ja khe-homelabi põhjal.',


    contextTitle: 'Kontekst',
    contextBody: 'Süsteeme kasutab kolm inimrühma. Pere kasutab pereteenuseid ja privaatseid rakendusi, avalikud külastajad loevad veebilehte ja mängivad mänge ning kutsutud külalised avavad reisi, mida on nendega jagatud. Süsteemid toetuvad mõnele välisteenusele: Cloudflare annab DNS-i, servavõrgu ja sisselogimise, GitHub koodi, CI ja konteineriregistri, Cloudflare R2 hoiab varukoopiaid väljaspool kodu, Telegram toob häireteated, AI-mudelite API-d loovad seiklusmängu jutustuse ja Elering annab mõõdetud energiaandmed.',
    viewContextTitle: 'Kontekstidiagramm',
    viewContextDesc: 'Süsteemid, neid kasutavad inimesed ja välisteenused, millest need sõltuvad.',
    elHousehold: 'Pere',
    elHouseholdSub: 'pereteenused, privaatrakendused',
    elVisitors: 'Avalikud külastajad',
    elVisitorsSub: 'veebileht ja mängud',
    elGuests: 'Reisikülalised',
    elGuestsSub: 'neile jagatud reis',
    groupPeople: 'Inimesed',
    groupExternal: 'Välisteenused',
    elEstate: 'KHE süsteemid',
    elEstateSub: 'tooted ja kodune platvorm',
    elCloudflare: 'Cloudflare',
    elCloudflareSub: 'DNS, sisselogimine',
    elGithub: 'GitHub',
    elGithubSub: 'kood, CI, GHCR',
    elR2: 'Cloudflare R2',
    elR2Sub: 'varukoopiad',
    elTelegram: 'Telegram',
    elTelegramSub: 'häireteated',
    elAiApis: 'AI-mudelid',
    elAiApisSub: 'mängu jutustus',
    elElering: 'Elering',
    elEleringSub: 'energiaandmed',
    relHousehold: 'kasutab',
    relVisitors: 'loevad, mängivad',
    relGuests: 'avavad reisi',

    blocksTitle: 'Ehitusplokid',
    blocksBody: 'Süsteemidel on neli osa. Tooted on see, mida inimesed kasutavad. Platvorm koodivaramus khe-homelab käitab neid: üks server, üks Dockeri virtuaalmasin ja iga teenus eraldi Compose\'i pinuna. Koduautomaatika töötab samal platvormil. Metakiht hoiab seda, mis ulatub üle mitme koodivaramu: agendi tööruumi, selle arhitektuuri ja privaatseid töömärkmeid.',
    viewBlocksTitle: 'Ehitusplokid',
    viewBlocksDesc: 'Tooted, platvorm, koduautomaatika ja metakiht ning nende seosed.',
    groupProducts: 'Tooted',
    groupPlatform: 'Platvorm (khe-homelab)',
    groupHouse: 'Koduautomaatika',
    groupMeta: 'Metakiht',
    elStudySub: 'õppemängud',
    elAdventureSub: 'AI-seltskonnamäng',
    elTripsSub: 'pere reisiatlas',
    elSitesSub: 'khe.ee ja mängukeskus',
    elEdge: 'Sissepääs',
    elEdgeSub: 'tunnel, pöördproksi, DNS',
    elRuntime: 'Rakenduste käitus',
    elRuntimeSub: 'lehed, mängud, reisid',
    elFamily: 'Pereteenused',
    elFamilySub: 'fotokogu',
    elObservability: 'Jälgitavus',
    elObservabilitySub: 'logid, häired',
    elBackup: 'Varundus ja taaste',
    elBackupSub: 'öösiti, kodust välja',
    elHouse: 'Koduautomaatika keskus',
    elHouseSub: 'ainult kohalikud seadmed',
    elWorkspaceSub: 'agendi tööruum',
    elArchitectureSub: 'otsused, indeks',
    elMetaSub: 'teekaart, plaanid',
    elProfileSub: 'GitHubi profiil',
    elEstfeedSub: 'HA energiaandmed',
    relRunOn: 'töötavad',
    stacksLabel: 'Pinud',
    privateLabel: 'privaatne',
    purposeKheStudy: 'Väikesed õppemängud Eesti õppekava järgi, staatilise rakendusena.',
    purposeKheAiAdventure: 'AI jutustatud seltskonnamäng, kus telefon käib käest kätte: staatiline kasutajaliides ja kaitstud AI-proksi, mõlemad konteinerikujutistena.',
    purposeKheTrips: 'Pere reisiatlas, privaatne ja Cloudflare Accessi taga. Üksikuid reise saab lingiga jagada.',
    purposeKheSites: 'See veebileht ja mängukeskus: lihtne HTML ja CSS, mille ehitavad Node\'i skriptid.',
    purposeEdge: 'Avalik liiklus väljuva tunneli kaudu, kohtvõrgu pöördproksi ja DNS ning põhiteenused: saadavuse kontroll, isetervendamine ja paroolihoidla.',
    purposeRuntime: 'Konteinerid avalike lehtede, mängude, jagatud lehtede ja reisiatlase taga.',
    purposeFamily: 'Pere fotokogu, millel on oma sisselogimine.',
    purposeObservability: 'Kõigi konteinerite logid ühes kohas ja häireteated telefoni.',
    purposeBackup: 'Öised andmebaasitõmmised ja failide varukoopiad viiakse kodust välja ning igal nädalal tehakse proovitaaste.',
    purposeHouse: 'Home Assistant ja selle kohalikud integratsioonid. Üksikasjad jäävad privaatseks.',
    purposeKheWorkspace: 'Juurkataloog, milles AI-kodeerimisagent töötab: agendi reeglid, commit\'i kontrollid ja koodivaramute loend.',
    purposeKheArchitecture: 'Süsteemide arhitektuuriotsused ja koodivaramute indeks, millest see leht ehitatakse.',
    purposeKheMeta: 'Privaatne töökiht: teekaart, plaanid ja maja dokumentatsioon.',
    purposeKhelias: 'GitHubi profiilileht.',
    purposeHaEstfeed: 'Eleringi mõõteandmete Home Assistanti integratsiooni edasiarendus (fork).',

    flowsTitle: 'Põhivood',
    requestTitle: 'Päringu teekond',
    requestBody: 'Külastaja päring jõuab esmalt Cloudflare\'i. Kodune server hoiab väljuvat tunnelit avatuna ja Cloudflare saadab iga hostinime päringud mööda seda õigesse konteinerisse, nii et koduruuter ei suuna midagi sisse. Kohtvõrgus vastab kohalik DNS samadele nimedele pöördproksi aadressiga, nii et pere seadmed jäävad kohtvõrku. Cloudflare Accessi taga olevatel rakendustel ei ole sellist otseteed.',
    viewRequestTitle: 'Päringu teekond',
    viewRequestDesc: 'Avalik päring läbi Cloudflare\'i ja tunneli ning pere päring kohtvõrgus.',
    groupInternet: 'Internetist',
    groupHomeNetwork: 'Kohtvõrgus',
    elVisitor: 'Külastaja',
    elVisitorSub: 'mis tahes brauser',
    elCfEdge: 'Cloudflare\'i serv',
    elCfEdgeSub: 'TLS, Access',
    elTunnel: 'Tunnel',
    elTunnelSub: 'ainult väljuv',
    elApp: 'Konteiner',
    elAppSub: 'Dockeri virtuaalmasinas',
    elLanClient: 'Pere seade',
    elLanClientSub: 'kohtvõrgus',
    elDns: 'Kohalik DNS',
    elDnsSub: 'sisevõrgu vastused',
    elProxy: 'Pöördproksi',
    elProxySub: 'wildcard-sertifikaat',
    relHttps: 'HTTPS',
    relPerHostname: 'hostinime järgi',
    relLookup: 'nimepäring',
    relPointsTo: 'suunab',
    deliveryTitle: 'Tarneprotsess',
    deliveryBody: 'Muudatus salvestatakse esmalt kohalikku koodivaramusse ja jõuab töösse siis, kui inimene selle GitHubi saadab. Konteinerikujutised ehitatakse ja skannitakse GitHubi käituril, avaldatakse GHCR-is koos SBOM-i ja päritoluandmetega ning kinnitatakse khe-homelabis räsi järgi PR-iga, mis liidetakse automaatselt, kui selle kaitse- ja atesteerimiskontrollid on läbitud. Seejärel tõmbab virtuaalmasina käitur kinnitatud kujutise. Staatilised lehed ei kasuta registrit: sama käitur ehitab ja kopeerib need.',
    viewDeliveryTitle: 'Tarneprotsess',
    viewDeliveryDesc: 'Commit\'ist töötava konteinerini.',
    elCommit: 'Commit',
    elCommitSub: 'agent valmistab,',
    elCommitSub2: 'inimene saadab',
    elCi: 'CI',
    elCiSub: 'GitHubi käitur',
    elCiSub2: 'ehitus, skann, atest',
    elGhcr: 'GHCR',
    elGhcrSub: 'avalikud kujutised,',
    elGhcrSub2: 'commit\'i sildiga',
    elPinPr: 'Kinnituse PR',
    elPinPrSub: 'khe-homelabis,',
    elPinPrSub2: 'liidetakse ise',
    elDeploy: 'Juurutus',
    elDeploySub: 'käitur virtuaalmasinas',
    elDeploySub2: 'tõmbab räsi järgi',

    qualityTitle: 'Kvaliteedieesmärgid',
    qualityIntro: 'Enamikku otsuseid kujundab viis eesmärki. Igal real on mehhanism ja koht, kust seda kontrollida.',
    qGoal: 'Eesmärk',
    qMechanism: 'Kuidas see täidetakse',
    qEvidence: 'Tõend',
    qSecurity: 'Turvalisus',
    qSecurityGoal: 'Kodu poole pääseb ainult serva kaudu.',
    qSecurityHow: 'Sissetulevaid porte ei ole, liiklus käib väljuva tunneli kaudu ja privaatsete rakenduste ees on Cloudflare Access. Kujutised skannitakse enne avaldamist ja nende atestaadid kontrollitakse enne kinnitamist.',
    qResilience: 'Töökindlus',
    qResilienceGoal: 'Rikke püüab kinni odavaim kiht, mis seda suudab.',
    qResilienceHow: 'Kihiti, riistvaralisest valvetaimerist välise seireni:',
    qResilienceRestore: 'Andmebaasitõmmised viiakse igal ööl kodust välja ja üks neist taastatakse igal nädalal.',
    qDelivery: 'Tarne',
    qDeliveryGoal: 'Mis töötab, on kirjas gitis.',
    qDeliveryHow: 'Saatmine main-harusse juurutab muudatuse. Kujutised on kinnitatud räsi järgi, nii et tagasipööramine on git-muudatus ja uuesti ehitatud virtuaalmasin teab, mida tõmmata.',
    qOperability: 'Hallatavus',
    qOperabilityGoal: 'Üks inimene haldab seda vabast ajast.',
    qOperabilityHow: 'Üks server, üks Dockeri virtuaalmasin ja iga teenus Compose\'i pinuna. Logid on ühes kohas ja häireteated jõuavad ühte telefoni.',
    qCost: 'Kulu',
    qCostGoal: 'Väike ja ettearvatav.',
    qCostHow: 'Riistvara on juba kodus ning serva ja CI jaoks piisab tasuta pakettidest. Väliste varukoopiate ja AI kasutuse eest makstakse kasutuse järgi ning mängu AI-proksil on päevane kululimiit.',
    readmeResilience: 'khe-homelabi töökindluse kihid',
    restoreWorkflow: 'iganädalane taastekontroll',

    decisionsTitle: 'Otsused',
    decisionsIntro: 'Süsteemide arhitektuuriotsused on hoiul koodivaramus <a href="https://github.com/khelias/khe-architecture">khe-architecture</a> ja avaldatakse siin täismahus, igaüks eraldi lehel. Asendatud otsused jäävad alles koos lingiga otsusele, mis need asendas.',
    decisionsInEnglish: 'Otsused on kirja pandud inglise keeles.',
    regTitle: 'Otsus',
    regStatus: 'Staatus',
    regDate: 'Kuupäev',
    statusAccepted: 'Vastu võetud',
    statusProposed: 'Ettepanek',
    statusSuperseded: 'Asendatud',
    statusDeprecated: 'Aegunud',
    productDecisions: 'Toodete endi otsused on nende koodivaramutes:',

    operatingTitle: 'Töökorraldus',
    operatingBody: 'Töö valmistab ette AI-kodeerimisagent ja töösse saadab selle inimene. Suurem muudatus algab kirjaliku plaaniga, millest inimene teeb agendile täitmiseks eesmärgi. Iga koodimuudatus vaadatakse plaani vastu üle ja iga commit läbib kontrolli, mis käivitab koodivaramu enda kontrollid ja otsib isikuandmeid. Ainult inimene saadab muudatused GitHubi ja saatmine main-harusse on juurutus.',
    viewOperatingTitle: 'Töökorraldus',
    viewOperatingDesc: 'Mida teeb agent ja mida inimene, plaanist juurutuseni.',
    laneAgent: 'Agent',
    laneOperator: 'Inimene',
    elPlan: 'Plaan',
    elPlanSub: 'kirjas failis',
    elApprove: 'Eesmärk',
    elApproveSub: 'kinnitatud plaan',
    elExecute: 'Täitmine',
    elExecuteSub: 'kohalikud muudatused',
    elReview: 'Ülevaatus',
    elReviewSub: 'võrdlus plaaniga',
    elGate: 'Commit\'i kontroll',
    elGateSub: 'kontroll, isikuandmed',
    elPush: 'Saatmine',
    elPushSub: 'ainult inimene, juurutab',

    limitsTitle: 'Piirangud ja suund',
    limitsIntro: 'Mis on veel nõrk:',
    limit1: 'Üks server on üksik rikkepunkt. Kui see või koduühendus on maas, on maas ka kõik avalikud lehed.',
    limit2: 'Täielikku taastamist tühjale virtuaalmasinale ei ole läbi proovitud. Taastet testitakse igal nädalal ühe andmebaasi kaupa, kuid tervikuna on taastamine tõendamata.',
    limit3: 'Üks asukoht ja üks servateenuse pakkuja. DNS, sertifikaadid, tunnel ja sisselogimine sõltuvad kõik Cloudflare\'ist.',
    directionIntro: 'Mis tuleb järgmisena:',
    next1: 'Staatilistele lehtedele teine asukoht, et need püsiksid üleval ka siis, kui homelab on maas.',
    next2: 'Taastamise proov ja selle põhjal kirjutatud käsiraamat enne, kui rakendusse jõuavad andmed, mis ei ole pere omad.',
    next3: 'Esimene rakenduse taustsüsteem khe-tripsile, otsuste <a href="/architecture/decisions/004/">ADR-004</a> ja <a href="/architecture/decisions/009/">ADR-009</a> mustri järgi.',
    next4: 'Mõõdetud arvud sellel lehel, näiteks saadavus ja taastamiste ajalugu, igaüks koos mõõtmise meetodiga.',

    backToRegister: 'Kõik otsused',
    decisionKicker: 'Arhitektuuriotsus',
    metaStatus: 'Staatus',
    metaDate: 'Kuupäev',
    metaSupersedes: 'Asendab',
    metaSupersededBy: 'Asendaja',
    metaRelated: 'Seotud',
    supersededNotice: 'Selle otsuse on asendanud',
    sourceOnGithub: 'Allikas GitHubis',
  },
};
