// Copy for the architecture page and the ADR pages. The build fills every
// empty data-i18n element from COPY.en and draws the diagram labels in every
// language, so the page reads without JS; architecture.js switches to COPY.et.
// ADR bodies stay English.
export const COPY = {
  en: {
    title: 'Estate architecture | KHE',
    description: 'A small software estate run from one machine at home: the estate in one picture, five decisions that shape it, how a change ships, how it stays up and where it is weak.',
    siteNavAria: 'Site navigation',
    homeLabel: 'KHE home',
    languageLabel: 'Language',
    siteKicker: 'KHE',
    siteTitle: 'Architecture',
    decisionSiteTitle: 'Decision',
    kicker: 'Estate architecture',
    headline: 'A small software estate, run from one machine at home.',
    lead: 'Three apps and a public website, built and run by one person with an AI coding agent. How the pieces fit, which decisions hold them together, and where it is still weak.',
    factsLabel: 'Three facts',
    factPorts: 'open inbound ports',
    factPortsNote: 'An outbound tunnel only.',
    factDigest: 'every image pinned by digest',
    factDigestNote: 'Scanned, attested, named in git.',
    factRestoreValue: 'weekly',
    factRestore: 'restore from offsite, tested',
    factRestoreNote: 'One dump restored each week.',
    restoreWorkflow: 'Restore check',
    tocLabel: 'On this page',
    navEstate: 'The estate',
    navKeyDecisions: 'Decisions',
    navShipping: 'Shipping a change',
    navUptime: 'Staying up',
    navRegister: 'All decisions',

    estateTitle: 'The estate in one picture',
    estateIntro: 'Traffic from the internet comes in through Cloudflare. Nothing at home listens on the internet.',
    viewEstateTitle: 'Estate diagram',
    viewEstateDesc: 'From the internet, people reach the estate through Cloudflare, which sends their traffic down an outbound tunnel to the home host. The host pulls images from GitHub and sends backups, alerts and AI calls out.',
    groupPeople: 'People',
    groupHost: 'Home host · one Docker VM',
    groupOutside: 'Outside',
    elHousehold: 'Household',
    elHouseholdSub: 'family services, private apps',
    elVisitors: 'Visitors',
    elVisitorsSub: 'website and games',
    elGuests: 'Trip guests',
    elGuestsSub: 'a trip shared with them',
    elCloudflare: 'Cloudflare',
    elCloudflareSub: 'DNS, TLS, sign-in for private apps',
    elEdge: 'Ingress',
    elEdgeSub: 'tunnel, reverse proxy, local DNS',
    elRuntime: 'App runtime',
    elRuntimeSub: 'sites, games, trips',
    elFamily: 'Family services',
    elFamilySub: 'photo library, own login',
    elObservability: 'Observability',
    elObservabilitySub: 'logs in one place, alerts',
    elBackup: 'Backup',
    elBackupSub: 'nightly dumps, offsite',
    elRunner: 'Deploy runner',
    elRunnerSub: 'pulls pinned images',
    elHouse: 'House automation',
    elHouseSub: 'Home Assistant, local devices only',
    elGithub: 'GitHub',
    elGithubSub: 'code, CI, image registry',
    elR2: 'Cloudflare R2',
    elR2Sub: 'offsite backups',
    elTelegram: 'Telegram',
    elTelegramSub: 'alerts to a phone',
    elAiApis: 'AI model APIs',
    elAiApisSub: 'game narration',
    relHttps: 'HTTPS',
    relTunnel: 'outbound tunnel',
    relImages: 'images',
    relBackups: 'backups',
    relAlerts: 'alerts',
    relAiCalls: 'AI calls',
    relHostOutside: 'images, backups, alerts',
    blocksSummary: 'What each block runs, and in which repo',
    groupProducts: 'Products',
    groupPlatform: 'Platform (khe-homelab)',
    groupHouse: 'House automation',
    groupMeta: 'Meta layer',
    stacksLabel: 'Stacks',
    privateLabel: 'private',
    purposeKheStudy: 'Small learning games for the Estonian curriculum, served as a static app.',
    purposeKheAiAdventure: 'An AI-narrated pass-the-phone party game: a static frontend and a guarded AI proxy, both shipped as images.',
    purposeKheTrips: 'The family trip atlas, private behind Cloudflare Access. Single trips can be shared by link.',
    purposeKheSites: 'This website and the games hub: plain HTML and CSS, built by Node scripts.',
    purposeEdge: 'Public traffic through the outbound tunnel, the reverse proxy and DNS on the home network, and the core services: uptime checks, self-healing and the password vault.',
    purposeRuntime: 'The containers behind the public sites, the games, the shared pages and the trip atlas.',
    purposeFamily: 'The family photo library, with its own login.',
    purposeObservability: 'Every container\'s logs in one place, and alerts to a phone.',
    purposeBackup: 'Nightly database dumps and file backups shipped offsite, and a test restore every week.',
    purposeRunner: 'The self-hosted GitHub Actions runner on the Docker VM. It pulls pinned images and builds the static sites.',
    purposeHouse: 'Home Assistant and its local integrations. The details stay private.',
    purposeKheWorkspace: 'The root an AI coding agent works in: the agent rules, the commit hooks and the list of repositories.',
    purposeKheArchitecture: 'The estate\'s architecture decisions and the estate index this page is built from.',
    purposeKheMeta: 'The private working layer: the roadmap, the plans and the house documentation.',
    purposeKhelias: 'The GitHub profile page.',
    purposeHaEstfeed: 'A fork of the Elering meter-data integration for Home Assistant.',

    keyDecisionsTitle: 'Five decisions that shape it',
    keyDecisionsIntro: 'Each one buys something and costs something. Both are written down.',
    buysLabel: 'Buys',
    costsLabel: 'Costs',
    readAdr: 'Read',
    kd011Title: 'No open ports at home',
    kd011Buys: 'The home line exposes nothing to scan, and Cloudflare absorbs floods before they reach the tunnel.',
    kd011Costs: 'One vendor carries DNS, certificates, the tunnel and sign-in.',
    kd010Title: 'One host, one Docker VM, Compose stacks',
    kd010Buys: 'One VM to back up, patch and rebuild, and one deploy path.',
    kd010Costs: 'No rolling updates. A host outage takes everything down.',
    kd008Title: 'Images built in CI, pinned by digest in git',
    kd008Buys: 'Git says what runs. A rollback is a commit, and a rebuilt VM knows what to pull.',
    kd008Costs: 'Every release crosses two repos: the app\'s CI, then a pin PR in khe-homelab.',
    kd001Title: 'A repo per product, each on its own stack',
    kd001Buys: 'Each product has its own CI, deploy and check, and upgrades on its own schedule.',
    kd001Costs: 'No shared code. A component is rebuilt in each repo that needs it.',
    kd006Title: 'Autonomy with minimal guards',
    kd006Buys: 'No review queue. The agent commits locally, a gate runs before every commit, a person pushes.',
    kd006Costs: 'A bad commit can still reach main. The GitHub account is a single point of failure.',
    registerTag: 'Register',
    moreDecisions: 'more decisions',
    moreDecisionsBody: 'All of them, with status and date, are listed below.',

    shippingTitle: 'How a change ships',
    shippingIntro: 'An agent prepares, a person pushes, machines do the rest. A push to main is a deploy.',
    viewShippingTitle: 'Shipping diagram',
    viewShippingDesc: 'Ten steps from a written plan to a running container, each marked with who does it: the agent, a person or a machine.',
    groupBeforePush: 'On the laptop · before the push',
    groupAfterPush: 'After the push · automated',
    tagAgent: 'AGENT',
    tagPerson: 'PERSON',
    tagHook: 'HOOK',
    tagCi: 'CI',
    tagRegistry: 'REGISTRY',
    tagHomelab: 'KHE-HOMELAB',
    tagVm: 'VM',
    elPlan: 'Plan',
    elPlanSub: 'written to a file',
    elApprove: 'Goal',
    elApproveSub: 'approves the plan',
    elExecute: 'Execute',
    elExecuteSub: 'local changes',
    elReview: 'Review',
    elReviewSub: 'diff against the plan',
    elGate: 'Commit gate',
    elGateSub: 'repo check, personal-data scan',
    elPush: 'Push',
    elPushSub: 'only a person, it deploys',
    elCi: 'Build',
    elCiSub: 'scan, SBOM, attest',
    elGhcr: 'GHCR',
    elGhcrSub: 'public image, by commit',
    elPinPr: 'Pin PR',
    elPinPrSub: 'merges itself after checks',
    elDeploy: 'Deploy',
    elDeploySub: 'runner pulls by digest',
    relPushDeploys: 'a push is a deploy',
    shippingNote: 'No person in the loop after the push: checks decide. Static sites skip the registry; the runner builds them.',

    uptimeTitle: 'How it stays up, and where it is weak',
    layersLabel: 'Five layers, cheapest first',
    layer1Title: 'Hardware watchdog',
    layer1Desc: 'resets the VM if the kernel hangs',
    layer1Time: '30 s',
    layer2Title: 'Autoheal',
    layer2Desc: 'restarts a container whose health check fails',
    layer2Time: 'on failure',
    layer3Title: 'Resource limits',
    layer3Desc: 'one runaway service cannot starve the VM',
    layer3Time: 'always',
    layer4Title: 'Uptime Kuma',
    layer4Desc: 'checks every service and alerts a phone',
    layer4Time: '~90 s',
    layer5Title: 'UptimeRobot',
    layer5Desc: 'checks khe.ee from outside the home',
    layer5Time: '5 min',
    backupLine: 'Database dumps and files go offsite to Cloudflare R2 every night, and one dump is restored every week to prove it works.',
    weakLabel: 'Still weak',
    weak1Title: 'One host, one home line.',
    weak1Body: 'If either is down, every public site is down.',
    weak2Title: 'The full rebuild is unproven.',
    weak2Body: 'Restores are tested one database at a time; a rebuild on an empty VM has never been rehearsed.',
    weak3Title: 'One edge vendor.',
    weak3Body: 'DNS, certificates, the tunnel and sign-in all depend on Cloudflare.',
    nextLabel: 'Next',
    next1: 'A second home for the static sites.',
    next2: 'A rebuild rehearsal, and the runbook written from it.',
    next3: 'The first app backend, for khe-trips (<a href="/architecture/decisions/004/">ADR-004</a>, <a href="/architecture/decisions/009/">ADR-009</a>).',
    next4: 'Measured uptime and restore history on this page.',

    decisionsTitle: 'All decisions',
    decisionsIntro: 'Kept in English in <a href="https://github.com/khelias/khe-architecture">khe-architecture</a>, one page each. Superseded decisions stay, with a link to the one that replaced them.',
    decisionsInEnglish: 'Decisions are kept in English.',
    regTitle: 'Decision',
    regStatus: 'Status',
    regDate: 'Date',
    statusAccepted: 'Accepted',
    statusProposed: 'Proposed',
    statusSuperseded: 'Superseded',
    statusDeprecated: 'Deprecated',
    productDecisions: 'The products keep their own decisions in their repositories:',

    backToRegister: 'All decisions',
    decisionKicker: 'Architecture decision',
    metaStatus: 'Status',
    metaDate: 'Date',
    metaSupersedes: 'Supersedes',
    metaSupersededBy: 'Superseded by',
    metaRelated: 'Related',
    supersededNotice: 'This decision is superseded by',
    sourceOnGithub: 'Source on GitHub',
  },
  et: {
    title: 'Arhitektuur | KHE',
    description: 'Väikesed tarkvarasüsteemid, mis töötavad ühes kodus asuvas serveris: süsteemid ühel pildil, viis neid kujundavat otsust, kuidas muudatus töösse jõuab, kuidas süsteemid töös püsivad ja kus on nõrgad kohad.',
    siteNavAria: 'Lehe navigeerimine',
    homeLabel: 'KHE avaleht',
    languageLabel: 'Keel',
    siteKicker: 'KHE',
    siteTitle: 'Arhitektuur',
    decisionSiteTitle: 'Otsus',
    kicker: 'Süsteemide arhitektuur',
    headline: 'Väikesed tarkvarasüsteemid, mis töötavad ühes kodus asuvas serveris.',
    lead: 'Kolm rakendust ja avalik veebileht, mida ehitab ja haldab üks inimene koos AI-kodeerimisagendiga. Siin on kirjas, kuidas osad kokku sobivad, millised otsused neid koos hoiavad ja kus on veel nõrkusi.',
    factsLabel: 'Kolm fakti',
    factPorts: 'avatud sissetulevat porti',
    factPortsNote: 'Ainult väljuv tunnel.',
    factDigest: 'iga konteinerikujutis on kinnitatud räsi järgi',
    factDigestNote: 'Skannitud, atesteeritud ja gitis kirjas.',
    factRestoreValue: 'iga nädal',
    factRestore: 'proovitaaste kodust väljas hoitud koopiast',
    factRestoreNote: 'Igal nädalal taastatakse üks tõmmis.',
    restoreWorkflow: 'Taastekontroll',
    tocLabel: 'Sellel lehel',
    navEstate: 'Süsteemid',
    navKeyDecisions: 'Otsused',
    navShipping: 'Muudatuse teekond',
    navUptime: 'Töökindlus',
    navRegister: 'Kõik otsused',

    estateTitle: 'Süsteemid ühel pildil',
    estateIntro: 'Internetist tulev liiklus jõuab koju Cloudflare\'i kaudu. Kodus ei ole internetile avatud ühtegi teenust.',
    viewEstateTitle: 'Süsteemide diagramm',
    viewEstateDesc: 'Internetist jõuavad inimesed süsteemideni Cloudflare\'i kaudu, mis saadab liikluse väljuva tunneli kaudu koduserverisse. Server tõmbab konteinerikujutised GitHubist ning saadab välja varukoopiad, häireteated ja AI-päringud.',
    groupPeople: 'Inimesed',
    groupHost: 'Koduserver · üks Dockeri virtuaalmasin',
    groupOutside: 'Väljaspool kodu',
    elHousehold: 'Pere',
    elHouseholdSub: 'pereteenused, privaatsed rakendused',
    elVisitors: 'Külastajad',
    elVisitorsSub: 'veebileht ja mängud',
    elGuests: 'Reisikülalised',
    elGuestsSub: 'neile jagatud reis',
    elCloudflare: 'Cloudflare',
    elCloudflareSub: 'DNS, TLS, privaatrakenduste sisselogimine',
    elEdge: 'Sissepääs',
    elEdgeSub: 'tunnel, pöördproksi, kohalik DNS',
    elRuntime: 'Rakenduste käitus',
    elRuntimeSub: 'lehed, mängud, reisid',
    elFamily: 'Pereteenused',
    elFamilySub: 'fotokogu, oma sisselogimine',
    elObservability: 'Jälgitavus',
    elObservabilitySub: 'logid ühes kohas, häired',
    elBackup: 'Varundus',
    elBackupSub: 'öised tõmmised, kodust väljas',
    elRunner: 'Juurutuse käitur',
    elRunnerSub: 'tõmbab kinnitatud kujutised',
    elHouse: 'Koduautomaatika',
    elHouseSub: 'Home Assistant, ainult kohalikud seadmed',
    elGithub: 'GitHub',
    elGithubSub: 'kood, CI, kujutiste register',
    elR2: 'Cloudflare R2',
    elR2Sub: 'varukoopiad kodust väljas',
    elTelegram: 'Telegram',
    elTelegramSub: 'häireteated telefoni',
    elAiApis: 'AI-mudelite API-d',
    elAiApisSub: 'mängu jutustus',
    relHttps: 'HTTPS',
    relTunnel: 'väljuv tunnel',
    relImages: 'kujutised',
    relBackups: 'varukoopiad',
    relAlerts: 'häired',
    relAiCalls: 'AI-päringud',
    relHostOutside: 'kujutised, varukoopiad, häired',
    blocksSummary: 'Mida iga osa käitab ja millises koodivaramus see asub',
    groupProducts: 'Tooted',
    groupPlatform: 'Platvorm (khe-homelab)',
    groupHouse: 'Koduautomaatika',
    groupMeta: 'Metakiht',
    stacksLabel: 'Pinud',
    privateLabel: 'privaatne',
    purposeKheStudy: 'Väikesed õppemängud Eesti õppekava järgi, staatilise rakendusena.',
    purposeKheAiAdventure: 'AI jutustatud seltskonnamäng, kus telefon käib käest kätte: staatiline kasutajaliides ja kaitstud AI-proksi, mõlemad konteinerikujutistena.',
    purposeKheTrips: 'Pere reisiatlas, privaatne ja Cloudflare Accessi taga. Üksikuid reise saab lingiga jagada.',
    purposeKheSites: 'See veebileht ja mängukeskus: lihtne HTML ja CSS, mille ehitavad Node\'i skriptid.',
    purposeEdge: 'Avalik liiklus väljuva tunneli kaudu, kohtvõrgu pöördproksi ja DNS ning põhiteenused: saadavuse kontroll, isetervendamine ja paroolihoidla.',
    purposeRuntime: 'Konteinerid avalike lehtede, mängude, jagatud lehtede ja reisiatlase taga.',
    purposeFamily: 'Pere fotokogu, millel on oma sisselogimine.',
    purposeObservability: 'Kõigi konteinerite logid ühes kohas ja häireteated telefoni.',
    purposeBackup: 'Öised andmebaasitõmmised ja failide varukoopiad viiakse kodust välja ning igal nädalal tehakse proovitaaste.',
    purposeRunner: 'Dockeri virtuaalmasinas töötav GitHub Actionsi käitur. See tõmbab kinnitatud konteinerikujutised ja ehitab staatilised lehed.',
    purposeHouse: 'Home Assistant ja selle kohalikud integratsioonid. Üksikasjad jäävad privaatseks.',
    purposeKheWorkspace: 'Juurkataloog, milles AI-kodeerimisagent töötab: agendi reeglid, commit\'i kontrollid ja koodivaramute loend.',
    purposeKheArchitecture: 'Süsteemide arhitektuuriotsused ja koodivaramute indeks, millest see leht ehitatakse.',
    purposeKheMeta: 'Privaatne töökiht: teekaart, plaanid ja maja dokumentatsioon.',
    purposeKhelias: 'GitHubi profiilileht.',
    purposeHaEstfeed: 'Eleringi mõõteandmete Home Assistanti integratsiooni edasiarendus (fork).',

    keyDecisionsTitle: 'Viis otsust, mis süsteeme kujundavad',
    keyDecisionsIntro: 'Iga otsus annab midagi ja maksab midagi. Mõlemad on kirja pandud.',
    buysLabel: 'Annab',
    costsLabel: 'Maksab',
    readAdr: 'Loe',
    kd011Title: 'Kodus ei ole avatud porte',
    kd011Buys: 'Koduühendusel ei ole midagi, mida skannida, ja Cloudflare neelab ülekoormusrünnakud enne, kui need tunnelini jõuavad.',
    kd011Costs: 'DNS, sertifikaadid, tunnel ja sisselogimine on ühe teenusepakkuja käes.',
    kd010Title: 'Üks server, üks Dockeri virtuaalmasin, Compose\'i pinud',
    kd010Buys: 'Varundada, paikata ja uuesti üles ehitada tuleb ühte virtuaalmasinat ning juurutusviis on üks.',
    kd010Costs: 'Järkjärgulisi uuendusi ei ole. Kui server on maas, on maas kõik.',
    kd008Title: 'Kujutised ehitatakse CI-s ja kinnitatakse gitis räsi järgi',
    kd008Buys: 'Git ütleb, mis töötab. Tagasipööramine on üks commit ja uuesti ehitatud virtuaalmasin teab, mida tõmmata.',
    kd008Costs: 'Iga väljalase läbib kaks koodivaramut: kõigepealt rakenduse CI, siis kinnituse PR khe-homelabis.',
    kd001Title: 'Igal tootel oma koodivaramu ja oma tehnoloogiad',
    kd001Buys: 'Igal tootel on oma CI, juurutus ja kontroll ning see uueneb oma ajakava järgi.',
    kd001Costs: 'Jagatud koodi ei ole. Komponent ehitatakse uuesti igas koodivaramus, mis seda vajab.',
    kd006Title: 'Autonoomia minimaalsete piirangutega',
    kd006Buys: 'Ülevaatuse järjekorda ei ole. Agent salvestab muudatused kohalikult, iga commit\'i eel käivitub kontroll ja GitHubi saadab muudatused inimene.',
    kd006Costs: 'Vigane commit võib siiski main-harusse jõuda. GitHubi konto on ainus rikkepunkt.',
    registerTag: 'Register',
    moreDecisions: 'otsust veel',
    moreDecisionsBody: 'Kõik otsused koos staatuse ja kuupäevaga on loetletud allpool.',

    shippingTitle: 'Kuidas muudatus töösse jõuab',
    shippingIntro: 'Agent valmistab ette, inimene saadab GitHubi ja ülejäänu teevad masinad. Saatmine main-harusse on juurutus.',
    viewShippingTitle: 'Tarneprotsessi diagramm',
    viewShippingDesc: 'Kümme sammu kirjalikust plaanist töötava konteinerini. Iga sammu juures on märgitud, kes selle teeb: agent, inimene või masin.',
    groupBeforePush: 'Sülearvutis · enne saatmist',
    groupAfterPush: 'Pärast saatmist · automaatselt',
    tagAgent: 'AGENT',
    tagPerson: 'INIMENE',
    tagHook: 'KONKS',
    tagCi: 'CI',
    tagRegistry: 'REGISTER',
    tagHomelab: 'KHE-HOMELAB',
    tagVm: 'VM',
    elPlan: 'Plaan',
    elPlanSub: 'kirjas failis',
    elApprove: 'Eesmärk',
    elApproveSub: 'kinnitab plaani',
    elExecute: 'Täitmine',
    elExecuteSub: 'kohalikud muudatused',
    elReview: 'Ülevaatus',
    elReviewSub: 'muudatuste võrdlus plaaniga',
    elGate: 'Eelkontroll',
    elGateSub: 'isikuandmete otsing, testid',
    elPush: 'Saatmine',
    elPushSub: 'ainult inimene, see juurutab',
    elCi: 'Ehitus',
    elCiSub: 'skannimine, SBOM, atesteerimine',
    elGhcr: 'GHCR',
    elGhcrSub: 'avalik kujutis commit\'i järgi',
    elPinPr: 'Kinnituse PR',
    elPinPrSub: 'liidetakse pärast kontrolle ise',
    elDeploy: 'Juurutus',
    elDeploySub: 'käitur tõmbab räsi järgi',
    relPushDeploys: 'saatmine on juurutus',
    shippingNote: 'Pärast saatmist inimest protsessis ei ole: otsustavad kontrollid. Staatilised lehed ei kasuta registrit, käitur ehitab need ise.',

    uptimeTitle: 'Kuidas süsteemid töös püsivad ja kus on nõrgad kohad',
    layersLabel: 'Viis kihti, odavaim esimesena',
    layer1Title: 'Riistvaraline valvetaimer',
    layer1Desc: 'taaskäivitab virtuaalmasina, kui tuum hangub',
    layer1Time: '30 s',
    layer2Title: 'Autoheal',
    layer2Desc: 'taaskäivitab konteineri, mille tervisekontroll ebaõnnestub',
    layer2Time: 'rikke korral',
    layer3Title: 'Ressursipiirangud',
    layer3Desc: 'üks kontrolli alt väljunud teenus ei jäta virtuaalmasinat ressurssideta',
    layer3Time: 'alati',
    layer4Title: 'Uptime Kuma',
    layer4Desc: 'kontrollib iga teenust ja saadab häire telefoni',
    layer4Time: '~90 s',
    layer5Title: 'UptimeRobot',
    layer5Desc: 'kontrollib khe.ee-d väljastpoolt kodu',
    layer5Time: '5 min',
    backupLine: 'Andmebaasitõmmised ja failid viiakse igal ööl kodust välja Cloudflare R2-sse. Igal nädalal taastatakse üks tõmmis, et kontrollida, kas taaste töötab.',
    weakLabel: 'Nõrgad kohad',
    weak1Title: 'Üks server, üks koduühendus.',
    weak1Body: 'Kui üks neist on maas, on maas kõik avalikud lehed.',
    weak2Title: 'Täielik ülesehitus on tõendamata.',
    weak2Body: 'Taastet testitakse ühe andmebaasi kaupa. Täielikku ülesehitust tühjal virtuaalmasinal ei ole kordagi läbi proovitud.',
    weak3Title: 'Üks servateenuse pakkuja.',
    weak3Body: 'DNS, sertifikaadid, tunnel ja sisselogimine sõltuvad kõik Cloudflare\'ist.',
    nextLabel: 'Edasi',
    next1: 'Staatilistele lehtedele teine asukoht.',
    next2: 'Ülesehituse proov ja selle põhjal kirjutatud käsiraamat.',
    next3: 'Esimene rakenduse taustsüsteem khe-tripsile (<a href="/architecture/decisions/004/">ADR-004</a>, <a href="/architecture/decisions/009/">ADR-009</a>).',
    next4: 'Mõõdetud saadavus ja taastamiste ajalugu sellel lehel.',

    decisionsTitle: 'Kõik otsused',
    decisionsIntro: 'Otsused on hoiul koodivaramus <a href="https://github.com/khelias/khe-architecture">khe-architecture</a> ja igaüks on avaldatud eraldi lehel. Asendatud otsused jäävad alles koos lingiga otsusele, mis need asendas.',
    decisionsInEnglish: 'Otsused on kirja pandud inglise keeles.',
    regTitle: 'Otsus',
    regStatus: 'Staatus',
    regDate: 'Kuupäev',
    statusAccepted: 'Vastu võetud',
    statusProposed: 'Ettepanek',
    statusSuperseded: 'Asendatud',
    statusDeprecated: 'Aegunud',
    productDecisions: 'Toodete endi otsused on nende koodivaramutes:',

    backToRegister: 'Kõik otsused',
    decisionKicker: 'Arhitektuuriotsus',
    metaStatus: 'Staatus',
    metaDate: 'Kuupäev',
    metaSupersedes: 'Asendab',
    metaSupersededBy: 'Asendaja',
    metaRelated: 'Seotud',
    supersededNotice: 'Selle otsuse on asendanud',
    sourceOnGithub: 'Allikas GitHubis',
  },
};
