// The architecture page's diagrams as code. Elements carry either a literal
// `name` (repo names are not translated) or a `label` key into
// src/landing/architecture/copy.js; `sub` keys are the smaller lines under it.
// `repo` and `groups` tie an element to khe-architecture ESTATE.md and the
// khe-homelab service groups; check.mjs fails when the two sides disagree.

export const elements = {
  people: { kind: 'boundary', label: 'groupPeople' },
  externals: { kind: 'boundary', label: 'groupExternal', labelBelow: true },
  household: { kind: 'person', label: 'elHousehold', sub: ['elHouseholdSub'] },
  visitors: { kind: 'person', label: 'elVisitors', sub: ['elVisitorsSub'] },
  guests: { kind: 'person', label: 'elGuests', sub: ['elGuestsSub'] },
  estate: { kind: 'system', label: 'elEstate', sub: ['elEstateSub'] },
  cloudflare: { kind: 'external', label: 'elCloudflare', sub: ['elCloudflareSub'] },
  github: { kind: 'external', label: 'elGithub', sub: ['elGithubSub'] },
  r2: { kind: 'external', label: 'elR2', sub: ['elR2Sub'] },
  telegram: { kind: 'external', label: 'elTelegram', sub: ['elTelegramSub'] },
  aiApis: { kind: 'external', label: 'elAiApis', sub: ['elAiApisSub'] },
  elering: { kind: 'external', label: 'elElering', sub: ['elEleringSub'] },

  products: { kind: 'boundary', label: 'groupProducts' },
  'khe-study': { kind: 'product', name: 'khe-study', repo: 'khe-study', sub: ['elStudySub'] },
  'khe-ai-adventure': { kind: 'product', name: 'khe-ai-adventure', repo: 'khe-ai-adventure', sub: ['elAdventureSub'] },
  'khe-trips': { kind: 'product', name: 'khe-trips', repo: 'khe-trips', sub: ['elTripsSub'] },
  'khe-sites': { kind: 'product', name: 'khe-sites', repo: 'khe-sites', sub: ['elSitesSub'] },
  platform: { kind: 'boundary', label: 'groupPlatform', repo: 'khe-homelab' },
  edge: { kind: 'platform', label: 'elEdge', sub: ['elEdgeSub'], groups: ['core'] },
  runtime: { kind: 'platform', label: 'elRuntime', sub: ['elRuntimeSub'], groups: ['apps'] },
  family: { kind: 'platform', label: 'elFamily', sub: ['elFamilySub'], groups: ['media'] },
  observability: { kind: 'platform', label: 'elObservability', sub: ['elObservabilitySub'], groups: ['observability'] },
  backup: { kind: 'platform', label: 'elBackup', sub: ['elBackupSub'] },
  houseGroup: { kind: 'boundary', label: 'groupHouse' },
  house: { kind: 'platform', label: 'elHouse', sub: ['elHouseSub'], groups: ['home'] },
  meta: { kind: 'boundary', label: 'groupMeta' },
  'khe-workspace': { kind: 'repo', name: 'khe-workspace', repo: 'khe-workspace', sub: ['elWorkspaceSub'] },
  'khe-architecture': { kind: 'repo', name: 'khe-architecture', repo: 'khe-architecture', sub: ['elArchitectureSub'] },
  'khe-meta': { kind: 'repo', name: 'khe-meta', repo: 'khe-meta', sub: ['elMetaSub'] },
  khelias: { kind: 'repo', name: 'khelias', repo: 'khelias', sub: ['elProfileSub'] },
  'ha-estfeed': { kind: 'repo', name: 'ha-estfeed', repo: 'ha-estfeed', sub: ['elEstfeedSub'] },

  internet: { kind: 'boundary', label: 'groupInternet' },
  homeNetwork: { kind: 'boundary', label: 'groupHomeNetwork' },
  visitor: { kind: 'person', label: 'elVisitor', sub: ['elVisitorSub'] },
  cfEdge: { kind: 'external', label: 'elCfEdge', sub: ['elCfEdgeSub'] },
  tunnel: { kind: 'platform', label: 'elTunnel', sub: ['elTunnelSub'] },
  app: { kind: 'platform', label: 'elApp', sub: ['elAppSub'] },
  lanClient: { kind: 'person', label: 'elLanClient', sub: ['elLanClientSub'] },
  dns: { kind: 'platform', label: 'elDns', sub: ['elDnsSub'] },
  proxy: { kind: 'platform', label: 'elProxy', sub: ['elProxySub'] },

  commit: { kind: 'step', label: 'elCommit', sub: ['elCommitSub', 'elCommitSub2'] },
  ci: { kind: 'external', label: 'elCi', sub: ['elCiSub', 'elCiSub2'] },
  ghcr: { kind: 'external', label: 'elGhcr', sub: ['elGhcrSub', 'elGhcrSub2'] },
  pinPr: { kind: 'step', label: 'elPinPr', sub: ['elPinPrSub', 'elPinPrSub2'] },
  deploy: { kind: 'platform', label: 'elDeploy', sub: ['elDeploySub', 'elDeploySub2'] },

  agentLane: { kind: 'boundary', label: 'laneAgent' },
  operatorLane: { kind: 'boundary', label: 'laneOperator' },
  plan: { kind: 'step', label: 'elPlan', sub: ['elPlanSub'] },
  approve: { kind: 'person', label: 'elApprove', sub: ['elApproveSub'] },
  execute: { kind: 'step', label: 'elExecute', sub: ['elExecuteSub'] },
  gate: { kind: 'step', label: 'elGate', sub: ['elGateSub'] },
  review: { kind: 'step', label: 'elReview', sub: ['elReviewSub'] },
  push: { kind: 'person', label: 'elPush', sub: ['elPushSub'] },
};

// Node geometry is [x, y, width, height] in the view's own coordinates.
// Edges route orthogonally (render-architecture.mjs); `route: 'tree'` fans
// out from the source's centre so several edges share one trunk.
export const views = [
  {
    id: 'context',
    title: 'viewContextTitle',
    desc: 'viewContextDesc',
    width: 960,
    height: 454,
    focus: 'estate',
    nodes: {
      people: [0, 0, 960, 110],
      household: [100, 36, 240, 62],
      visitors: [360, 36, 240, 62],
      guests: [620, 36, 240, 62],
      estate: [120, 184, 720, 76],
      externals: [0, 336, 960, 118],
      cloudflare: [11, 352, 152, 64],
      github: [168, 352, 152, 64],
      r2: [325, 352, 152, 64],
      telegram: [482, 352, 152, 64],
      aiApis: [639, 352, 152, 64],
      elering: [796, 352, 152, 64],
    },
    edges: [
      { from: 'household', to: 'estate', label: 'relHousehold' },
      { from: 'visitors', to: 'estate', label: 'relVisitors' },
      { from: 'guests', to: 'estate', label: 'relGuests' },
      { from: 'estate', to: 'cloudflare', route: 'tree' },
      { from: 'estate', to: 'github', route: 'tree' },
      { from: 'estate', to: 'r2', route: 'tree' },
      { from: 'estate', to: 'telegram', route: 'tree' },
      { from: 'estate', to: 'aiApis', route: 'tree' },
      { from: 'estate', to: 'elering', route: 'tree' },
    ],
  },
  {
    id: 'blocks',
    title: 'viewBlocksTitle',
    desc: 'viewBlocksDesc',
    width: 960,
    height: 488,
    focus: 'runtime',
    nodes: {
      products: [0, 0, 960, 112],
      'khe-study': [12, 36, 225, 62],
      'khe-ai-adventure': [249, 36, 225, 62],
      'khe-trips': [486, 36, 225, 62],
      'khe-sites': [723, 36, 225, 62],
      platform: [0, 150, 710, 188],
      edge: [12, 186, 221, 62],
      runtime: [245, 186, 221, 62],
      family: [478, 186, 221, 62],
      observability: [12, 262, 221, 62],
      backup: [245, 262, 221, 62],
      houseGroup: [722, 150, 238, 188],
      house: [731, 186, 220, 62],
      meta: [0, 376, 960, 112],
      'khe-workspace': [12, 412, 177, 62],
      'khe-architecture': [201, 412, 177, 62],
      'khe-meta': [390, 412, 177, 62],
      khelias: [579, 412, 177, 62],
      'ha-estfeed': [768, 412, 180, 62],
    },
    edges: [
      { from: 'products', to: 'platform', label: 'relRunOn' },
    ],
  },
  {
    id: 'request',
    title: 'viewRequestTitle',
    desc: 'viewRequestDesc',
    width: 960,
    height: 264,
    focus: 'tunnel',
    nodes: {
      internet: [0, 0, 732, 118],
      visitor: [12, 36, 172, 66],
      cfEdge: [280, 36, 172, 66],
      tunnel: [548, 36, 172, 66],
      homeNetwork: [0, 146, 732, 118],
      lanClient: [12, 182, 172, 66],
      dns: [280, 182, 172, 66],
      proxy: [548, 182, 172, 66],
      app: [764, 36, 192, 212],
    },
    edges: [
      { from: 'visitor', to: 'cfEdge', label: 'relHttps' },
      { from: 'cfEdge', to: 'tunnel', label: 'relPerHostname' },
      { from: 'tunnel', to: 'app' },
      { from: 'lanClient', to: 'dns', label: 'relLookup' },
      { from: 'dns', to: 'proxy', label: 'relPointsTo', dashed: true },
      { from: 'proxy', to: 'app' },
    ],
  },
  {
    id: 'delivery',
    title: 'viewDeliveryTitle',
    desc: 'viewDeliveryDesc',
    width: 960,
    height: 96,
    focus: 'pinPr',
    nodes: {
      commit: [1, 8, 178, 80],
      ci: [196, 8, 178, 80],
      ghcr: [391, 8, 178, 80],
      pinPr: [586, 8, 178, 80],
      deploy: [781, 8, 178, 80],
    },
    edges: [
      { from: 'commit', to: 'ci' },
      { from: 'ci', to: 'ghcr' },
      { from: 'ghcr', to: 'pinPr' },
      { from: 'pinPr', to: 'deploy' },
    ],
  },
  {
    id: 'operating',
    title: 'viewOperatingTitle',
    desc: 'viewOperatingDesc',
    width: 960,
    height: 292,
    focus: 'gate',
    nodes: {
      agentLane: [0, 0, 960, 124],
      plan: [12, 38, 204, 66],
      execute: [256, 38, 204, 66],
      review: [500, 38, 204, 66],
      gate: [744, 38, 204, 66],
      operatorLane: [0, 168, 960, 124],
      approve: [12, 206, 204, 66],
      push: [744, 206, 204, 66],
    },
    edges: [
      { from: 'plan', to: 'approve' },
      { from: 'approve', to: 'execute' },
      { from: 'execute', to: 'review' },
      { from: 'review', to: 'gate' },
      { from: 'gate', to: 'push' },
    ],
  },
];

// The building-block cards below the diagram, in reading order.
export const blockCards = [
  { group: 'groupProducts', ids: ['khe-study', 'khe-ai-adventure', 'khe-trips', 'khe-sites'] },
  { group: 'groupPlatform', repo: 'khe-homelab', ids: ['edge', 'runtime', 'family', 'observability', 'backup'] },
  { group: 'groupHouse', ids: ['house'] },
  { group: 'groupMeta', ids: ['khe-workspace', 'khe-architecture', 'khe-meta', 'khelias', 'ha-estfeed'] },
];

// Product repos keep their own decisions; the page links the directories.
export const productDecisionDirs = [
  { repo: 'khe-study', url: 'https://github.com/khelias/khe-study/tree/main/docs/adr' },
  { repo: 'khe-ai-adventure', url: 'https://github.com/khelias/khe-ai-adventure/tree/main/docs/decisions' },
];
