// The architecture page's diagrams as code. Elements carry either a literal
// `name` (repo names are not translated) or a `label` key into
// src/landing/architecture/copy.js; `sub` keys are the smaller lines under it.
// `repo` and `groups` tie an element to khe-architecture ESTATE.md and the
// khe-homelab service groups; check.mjs fails when the two sides disagree.

export const elements = {
  household: { kind: 'person', label: 'elHousehold', sub: ['elHouseholdSub'] },
  visitors: { kind: 'person', label: 'elVisitors', sub: ['elVisitorsSub'] },
  guests: { kind: 'person', label: 'elGuests', sub: ['elGuestsSub'] },
  estate: { kind: 'system', label: 'elEstate', sub: ['elEstateSub'] },
  cloudflare: { kind: 'external', label: 'elCloudflare', sub: ['elCloudflareSub'] },
  github: { kind: 'external', label: 'elGithub', sub: ['elGithubSub'] },
  r2: { kind: 'external', label: 'elR2', sub: ['elR2Sub'] },
  telegram: { kind: 'external', label: 'elTelegram', sub: ['elTelegramSub'] },
  aiApis: { kind: 'external', label: 'elAiApis', sub: ['elAiApisSub'] },
  elering: { kind: 'external', label: 'elElering', sub: ['elEleringSub'] },

  products: { kind: 'boundary', label: 'groupProducts' },
  'khe-study': { kind: 'product', name: 'khe-study', repo: 'khe-study', sub: ['elStudySub'] },
  'khe-ai-adventure': { kind: 'product', name: 'khe-ai-adventure', repo: 'khe-ai-adventure', sub: ['elAdventureSub'] },
  'khe-trips': { kind: 'product', name: 'khe-trips', repo: 'khe-trips', sub: ['elTripsSub'] },
  'khe-sites': { kind: 'product', name: 'khe-sites', repo: 'khe-sites', sub: ['elSitesSub'] },
  platform: { kind: 'boundary', label: 'groupPlatform', repo: 'khe-homelab' },
  edge: { kind: 'platform', label: 'elEdge', sub: ['elEdgeSub'], groups: ['core'] },
  runtime: { kind: 'platform', label: 'elRuntime', sub: ['elRuntimeSub'], groups: ['apps'] },
  family: { kind: 'platform', label: 'elFamily', sub: ['elFamilySub'], groups: ['media'] },
  observability: { kind: 'platform', label: 'elObservability', sub: ['elObservabilitySub'], groups: ['observability'] },
  backup: { kind: 'platform', label: 'elBackup', sub: ['elBackupSub'] },
  houseGroup: { kind: 'boundary', label: 'groupHouse' },
  house: { kind: 'platform', label: 'elHouse', sub: ['elHouseSub'], groups: ['home'] },
  meta: { kind: 'boundary', label: 'groupMeta' },
  'khe-workspace': { kind: 'repo', name: 'khe-workspace', repo: 'khe-workspace', sub: ['elWorkspaceSub'] },
  'khe-architecture': { kind: 'repo', name: 'khe-architecture', repo: 'khe-architecture', sub: ['elArchitectureSub'] },
  'khe-meta': { kind: 'repo', name: 'khe-meta', repo: 'khe-meta', sub: ['elMetaSub'] },
  khelias: { kind: 'repo', name: 'khelias', repo: 'khelias', sub: ['elProfileSub'] },
  'ha-estfeed': { kind: 'repo', name: 'ha-estfeed', repo: 'ha-estfeed', sub: ['elEstfeedSub'] },

  visitor: { kind: 'person', label: 'elVisitor', sub: ['elVisitorSub'] },
  cfEdge: { kind: 'external', label: 'elCfEdge', sub: ['elCfEdgeSub'] },
  tunnel: { kind: 'platform', label: 'elTunnel', sub: ['elTunnelSub'] },
  app: { kind: 'platform', label: 'elApp', sub: ['elAppSub'] },
  lanClient: { kind: 'person', label: 'elLanClient', sub: ['elLanClientSub'] },
  dns: { kind: 'platform', label: 'elDns', sub: ['elDnsSub'] },
  proxy: { kind: 'platform', label: 'elProxy', sub: ['elProxySub'] },

  commit: { kind: 'step', label: 'elCommit', sub: ['elCommitSub', 'elCommitSub2'] },
  ci: { kind: 'external', label: 'elCi', sub: ['elCiSub', 'elCiSub2'] },
  ghcr: { kind: 'external', label: 'elGhcr', sub: ['elGhcrSub', 'elGhcrSub2'] },
  pinPr: { kind: 'step', label: 'elPinPr', sub: ['elPinPrSub', 'elPinPrSub2'] },
  deploy: { kind: 'platform', label: 'elDeploy', sub: ['elDeploySub', 'elDeploySub2'] },

  agentLane: { kind: 'boundary', label: 'laneAgent' },
  operatorLane: { kind: 'boundary', label: 'laneOperator' },
  plan: { kind: 'step', label: 'elPlan', sub: ['elPlanSub'] },
  approve: { kind: 'person', label: 'elApprove', sub: ['elApproveSub'] },
  execute: { kind: 'step', label: 'elExecute', sub: ['elExecuteSub'] },
  gate: { kind: 'step', label: 'elGate', sub: ['elGateSub'] },
  review: { kind: 'step', label: 'elReview', sub: ['elReviewSub'] },
  push: { kind: 'person', label: 'elPush', sub: ['elPushSub'] },
  ship: { kind: 'external', label: 'elShip', sub: ['elShipSub'] },
};

// Node geometry is [x, y, width, height] in the view's own coordinates.
export const views = [
  {
    id: 'context',
    title: 'viewContextTitle',
    desc: 'viewContextDesc',
    width: 960,
    height: 460,
    focus: 'estate',
    nodes: {
      household: [40, 20, 220, 60],
      visitors: [370, 20, 220, 60],
      guests: [700, 20, 220, 60],
      estate: [320, 196, 320, 68],
      cloudflare: [10, 380, 145, 60],
      github: [168, 380, 145, 60],
      r2: [326, 380, 145, 60],
      telegram: [484, 380, 145, 60],
      aiApis: [642, 380, 145, 60],
      elering: [800, 380, 150, 60],
    },
    edges: [
      { from: 'household', to: 'estate', label: 'relHousehold' },
      { from: 'visitors', to: 'estate', label: 'relVisitors' },
      { from: 'guests', to: 'estate', label: 'relGuests' },
      { from: 'estate', to: 'cloudflare' },
      { from: 'estate', to: 'github' },
      { from: 'estate', to: 'r2' },
      { from: 'estate', to: 'telegram' },
      { from: 'estate', to: 'aiApis' },
      { from: 'estate', to: 'elering' },
    ],
  },
  {
    id: 'blocks',
    title: 'viewBlocksTitle',
    desc: 'viewBlocksDesc',
    width: 960,
    height: 530,
    focus: 'runtime',
    nodes: {
      products: [10, 10, 460, 200],
      'khe-study': [30, 48, 200, 60],
      'khe-ai-adventure': [250, 48, 200, 60],
      'khe-trips': [30, 128, 200, 60],
      'khe-sites': [250, 128, 200, 60],
      meta: [490, 10, 460, 200],
      'khe-workspace': [506, 48, 138, 60],
      'khe-architecture': [656, 48, 138, 60],
      'khe-meta': [806, 48, 128, 60],
      khelias: [506, 128, 138, 60],
      'ha-estfeed': [656, 128, 138, 60],
      platform: [10, 290, 700, 230],
      edge: [30, 328, 210, 60],
      runtime: [255, 328, 210, 60],
      family: [480, 328, 210, 60],
      observability: [30, 438, 210, 60],
      backup: [255, 438, 210, 60],
      houseGroup: [730, 290, 220, 230],
      house: [745, 328, 190, 60],
    },
    edges: [
      { from: 'products', to: 'platform', label: 'relRunOn', points: [[240, 210], [240, 290]] },
      { from: 'edge', to: 'runtime' },
      { from: 'runtime', to: 'family' },
      { from: 'observability', to: 'runtime' },
      { from: 'backup', to: 'family' },
    ],
  },
  {
    id: 'request',
    title: 'viewRequestTitle',
    desc: 'viewRequestDesc',
    width: 960,
    height: 280,
    focus: 'tunnel',
    nodes: {
      visitor: [10, 30, 165, 60],
      cfEdge: [265, 30, 165, 60],
      tunnel: [520, 30, 165, 60],
      app: [750, 110, 200, 60],
      lanClient: [10, 190, 165, 60],
      dns: [265, 190, 165, 60],
      proxy: [520, 190, 165, 60],
    },
    edges: [
      { from: 'visitor', to: 'cfEdge', label: 'relHttps' },
      { from: 'cfEdge', to: 'tunnel', label: 'relPerHostname' },
      { from: 'tunnel', to: 'app' },
      { from: 'lanClient', to: 'dns', label: 'relLookup' },
      { from: 'dns', to: 'proxy', label: 'relPointsTo', dashed: true },
      { from: 'proxy', to: 'app' },
    ],
  },
  {
    id: 'delivery',
    title: 'viewDeliveryTitle',
    desc: 'viewDeliveryDesc',
    width: 960,
    height: 120,
    focus: 'pinPr',
    nodes: {
      commit: [10, 20, 166, 76],
      ci: [204, 20, 166, 76],
      ghcr: [398, 20, 166, 76],
      pinPr: [592, 20, 166, 76],
      deploy: [786, 20, 166, 76],
    },
    edges: [
      { from: 'commit', to: 'ci' },
      { from: 'ci', to: 'ghcr' },
      { from: 'ghcr', to: 'pinPr' },
      { from: 'pinPr', to: 'deploy' },
    ],
  },
  {
    id: 'operating',
    title: 'viewOperatingTitle',
    desc: 'viewOperatingDesc',
    width: 960,
    height: 300,
    focus: 'gate',
    nodes: {
      agentLane: [10, 10, 940, 120],
      plan: [30, 46, 200, 60],
      execute: [260, 46, 200, 60],
      review: [490, 46, 200, 60],
      gate: [720, 46, 210, 60],
      operatorLane: [10, 170, 940, 120],
      approve: [145, 206, 200, 60],
      push: [490, 206, 200, 60],
      ship: [720, 206, 210, 60],
    },
    edges: [
      { from: 'plan', to: 'approve' },
      { from: 'approve', to: 'execute' },
      { from: 'execute', to: 'review' },
      { from: 'review', to: 'gate' },
      { from: 'gate', to: 'push' },
      { from: 'push', to: 'ship' },
    ],
  },
];

// The building-block cards below the diagram, in reading order.
export const blockCards = [
  { group: 'groupProducts', ids: ['khe-study', 'khe-ai-adventure', 'khe-trips', 'khe-sites'] },
  { group: 'groupPlatform', repo: 'khe-homelab', ids: ['edge', 'runtime', 'family', 'observability', 'backup'] },
  { group: 'groupHouse', ids: ['house'] },
  { group: 'groupMeta', ids: ['khe-workspace', 'khe-architecture', 'khe-meta', 'khelias', 'ha-estfeed'] },
];

// Product repos keep their own decisions; the page links the directories.
export const productDecisionDirs = [
  { repo: 'khe-study', url: 'https://github.com/khelias/khe-study/tree/main/docs/adr' },
  { repo: 'khe-ai-adventure', url: 'https://github.com/khelias/khe-ai-adventure/tree/main/docs/decisions' },
];
